In [22]:
# import packages
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
df = pd.read_csv("../data/electric_vehicles.csv", sep=";", index_col=0)
df['City'] = df['City'].str.replace('\d+ ', '')

C:\Users\jchop\AppData\Local\Temp/ipykernel_48440/1959812668.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['City'] = df['City'].str.replace('\d+ ', '')

In [51]:
growth_rate_2021=(df["2021"]-df["2020"])/df["2020"]
growth_rate_2020=(df["2020"]-df["2019"])/df["2019"]
growth_rate_2019=(df["2019"]-df["2018"])/df["2018"]
growth_rate_2018=(df["2018"]-df["2017"])/df["2017"]
growth_rate_mean=(growth_rate_2021+growth_rate_2020+growth_rate_2019+growth_rate_2018)/4
df["2022_pred"] = round(df["2021"]*(1+growth_rate_mean))
df["2023_pred"] = round(df["2021"]*((1+growth_rate_mean)**2))
df["2024_pred"] = round(df["2021"]*((1+growth_rate_mean)**3))
df

,City,2017,2018,2019,2020,2021,2022_pred,2023_pred,2024_pred
Index,,,,,,,,,
1,Aeugst am Albis,7,8,13,27,39,61.0,96.0,152.0
2,Affoltern am Albis,29,35,54,75,103,142.0,196.0,270.0
3,Bonstetten,18,21,29,37,70,100.0,143.0,204.0
4,Hausen am Albis,16,21,25,32,45,58.0,76.0,98.0
5,Hedingen,14,22,31,45,56,79.0,113.0,160.0
...,...,...,...,...,...,...,...,...,...
6806,Vendlincourt,0,0,0,0,3,NaN,NaN,NaN
6807,Basse-Allaine,2,2,3,5,9,13.0,20.0,30.0
6808,Clos du Doubs,0,0,2,6,9,NaN,NaN,NaN
6809,Haute-Ajoie,0,0,1,1,2,NaN,NaN,NaN
6810,La Baroche,3,2,3,5,6,8.0,10.0,12.0

In [52]:
dv_ev_final = pd.read_excel("../data/excel.xlsx")
dv_ev_final

                   City  Count
0     Gondiswil Schweiz    1.0
1                Sattel    1.0
2               Steinen    3.0
3                Aadorf    2.0
4                 Aarau   16.0
...                 ...    ...
1113               Zuoz    2.0
1114             Zuzwil    3.0
1115           Zweidlen    1.0
1116         Zweisimmen    6.0
1117             ZÃ¼rich   39.0

[1118 rows x 2 columns]

In [53]:
df = pd.merge(df, dv_ev_final, on="City", how="right")
df

,City,2017,2018,2019,2020,2021,2022_pred,2023_pred,2024_pred,Count
0,Gondiswil Schweiz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,Sattel,1.0,4.0,7.0,9.0,11.0,23.0,47.0,97.0,1.0
2,Steinen,11.0,10.0,15.0,17.0,27.0,35.0,44.0,57.0,3.0
3,Aadorf,29.0,31.0,43.0,69.0,135.0,203.0,305.0,460.0,2.0
4,Aarau,44.0,67.0,106.0,145.0,227.0,343.0,517.0,781.0,16.0
...,...,...,...,...,...,...,...,...,...,...
1113,Zuoz,1.0,1.0,3.0,5.0,9.0,17.0,31.0,59.0,2.0
1114,Zuzwil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1115,Zweidlen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1116,Zweisimmen,3.0,5.0,7.0,11.0,15.0,23.0,34.0,51.0,6.0
1117,ZÃ¼rich,815.0,940.0,1392.0,2036.0,3017.0,4208.0,5868.0,8185.0,39.0

In [54]:
df["recomm_2022"] = round(df["Count"]*(1+(df["2022_pred"]-df["2021"])/df["2021"]))
df["recomm_2023"] = round(df["recomm_2022"]*(1+(df["2023_pred"]-df["2022_pred"])/df["2022_pred"]))
df["recom_2024"] = round(df["recomm_2023"]*(1+(df["2024_pred"]-df["2023_pred"])/df["2023_pred"]))
df

,City,2017,2018,2019,2020,2021,2022_pred,2023_pred,2024_pred,Count,recomm_2022,recomm_2023,recom_2024
0,Gondiswil Schweiz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,Sattel,1.0,4.0,7.0,9.0,11.0,23.0,47.0,97.0,1.0,2.0,4.0,8.0
2,Steinen,11.0,10.0,15.0,17.0,27.0,35.0,44.0,57.0,3.0,4.0,5.0,6.0
3,Aadorf,29.0,31.0,43.0,69.0,135.0,203.0,305.0,460.0,2.0,3.0,5.0,8.0
4,Aarau,44.0,67.0,106.0,145.0,227.0,343.0,517.0,781.0,16.0,24.0,36.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,Zuoz,1.0,1.0,3.0,5.0,9.0,17.0,31.0,59.0,2.0,4.0,7.0,13.0
1114,Zuzwil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
1115,Zweidlen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1116,Zweisimmen,3.0,5.0,7.0,11.0,15.0,23.0,34.0,51.0,6.0,9.0,13.0,20.0
1117,ZÃ¼rich,815.0,940.0,1392.0,2036.0,3017.0,4208.0,5868.0,8185.0,39.0,54.0,75.0,105.0